export const VENCIMENTO = {
  SEMANA: "Nesta semana",
  MES: "Neste mês",
  SEM_FILTRO: "Sem filtro",
};

export const FILTRO = {
  DAQUI_A_30_DIAS: "daqui_a_30_dias",
  DAQUI_A_7_DIAS: "daqui_a_7_dias",
  SEM_FILTRO: "sem_filtro",
};

export const STATUS = {
  AUTORIZADAS: "AUTORIZADAS",
  PENDENTES: "PENDENTES",
  CANCELADAS: "CANCELADAS",
  RECUSADAS: "RECUSADAS",
  QUESTIONADAS: "QUESTIONADAS",
};

export const STATUS_ALIMENTO = {
  RECEBIDO: "RECEBIDO",
  PARCIAL: "PARCIAL",
  NAO_RECEBIDO: "NAO_RECEBIDO",
};

export const STATUS_GUIA = {
  PENDENTE: "PENDENTE_DE_CONFERENCIA",
  RECEBIDA: "RECEBIDA",
  PARCIAL: "RECEBIMENTO_PARCIAL",
  NAO_RECEBIDO: "NAO_RECEBIDA",
  REPOSICAO_PARCIAL: "REPOSICAO_PARCIAL",
  REPOSICAO_TOTAL: "REPOSICAO_TOTAL",
};
