export var statusEnum = {
  RASCUNHO: "RASCUNHO",
  DRE_A_VALIDAR: "DRE_A_VALIDAR",
  DRE_APROVADO: "DRE_APROVADO",
  CODAE_A_VALIDAR: "CODAE_A_VALIDAR",
  CODAE_APROVADO: "CODAE_APROVADO",
  TERCEIRIZADA_TOMA_CIENCIA: "TERCEIRIZADA_TOMA_CIENCIA"
};
