export const PERFIL = {
  DIRETOR: `"DIRETOR"`,
  ADMINISTRADOR_ESCOLA: `"ADMINISTRADOR_ESCOLA"`,
  SUPLENTE: `"SUPLENTE"`,
  COGESTOR: `"COGESTOR"`,
  ADMINISTRADOR_DRE: `"ADMINISTRADOR_DRE"`,
  COORDENADOR_GESTAO_ALIMENTACAO_TERCEIRIZADA: `"COORDENADOR_GESTAO_ALIMENTACAO_TERCEIRIZADA"`,
  ADMINISTRADOR_GESTAO_ALIMENTACAO_TERCEIRIZADA: `"ADMINISTRADOR_GESTAO_ALIMENTACAO_TERCEIRIZADA"`,
  COORDENADOR_DIETA_ESPECIAL: `"COORDENADOR_DIETA_ESPECIAL"`,
  ADMINISTRADOR_DIETA_ESPECIAL: `"ADMINISTRADOR_DIETA_ESPECIAL"`
};

export const TIPO_PERFIL = {
  ESCOLA: `"escola"`,
  DIRETORIA_REGIONAL: `"diretoriaregional"`,
  GESTAO_ALIMENTACAO_TERCEIRIZADA: `"gestao_alimentacao_terceirizada"`,
  DIETA_ESPECIAL: `"dieta_especial"`,
  TERCEIRIZADA: `"terceirizada"`
};

export const ENTER = 13;

export const DOIS_MB = 2097152;
